CREATE TABLE IF NOT EXISTS "File" (
    "id" VARCHAR PRIMARY KEY,
    "fileName" VARCHAR(255) NOT NULL,
    "fileType" VARCHAR(255) NOT NULL,
    "fileExtension" VARCHAR(255) NOT NULL,
    "fileSize" INT NOT NULL,
    "fileUrl" VARCHAR(255) NOT NULL,
    "userId" VARCHAR REFERENCES "UserAccount" (id) ON DELETE CASCADE,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);