name: Node.js CD
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        script: |
          cd generic-project-backend
          git add .
          git stash
          git pull origin main
          git stash pop
          npm install
          npm run build
          pm2 restart generic-project-backend


